# Generated by Django 2.1.5 on 2019-01-24 01:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tickers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10)),
                ('price', models.FloatField()),
                ('upside', models.FloatField()),
                ('downside', models.FloatField()),
                ('u_val', models.FloatField()),
                ('atr', models.FloatField()),
                ('stop', models.FloatField()),
                ('risk_unit', models.FloatField()),
                ('position', models.IntegerField()),
                ('support', models.FloatField()),
                ('resistance', models.FloatField()),
                ('notes', models.TextField()),
                ('concerns', models.TextField()),
                ('date_registered', models.DateField(default=django.utils.timezone.now)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
